name: Code scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 19 * * *'

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit
      - name: Run Detekt
        continue-on-error: true
        run: ./gradlew detektMetadataMain --continue
      - name: Merge Detekt reports
        run: ./gradlew detektMerge
      - name: Submit Detekt report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/reports/detekt/merge.sarif
